### ISSUE TITLE
Error thrown whenever message is sent (making plugin unusable

### ISSUE THREAD

**Issue by Vaela-V** [yakovliam/YakoChat#1]
`2019-12-10 14:04:44.802 [main] FATAL - Could not pass event "cn.nukkit.event.player.PlayerChatEvent" to "YakoChat v1.4": null on me.yakovliam.nkdev.yakochat.event.Chat
2019-12-10 14:04:44.805 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[kok.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[kok.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[kok.jar:?]
	at cn.nukkit.Player.chat(Player.java:3318) ~[kok.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2782) ~[kok.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_222]
	at cn.nukkit.network.Network.processPackets(Network.java:197) [kok.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:180) [kok.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2092) [kok.jar:?]
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [kok.jar:?]
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [kok.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [kok.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:83) [kok.jar:?]
	at cn.nukkit.Server.tick(Server.java:1124) [kok.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:903) [kok.jar:?]
	at cn.nukkit.Server.start(Server.java:880) [kok.jar:?]
	at cn.nukkit.Server.<init>(Server.java:565) [kok.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [kok.jar:?]
Caused by: java.lang.NullPointerException
	at me.yakovliam.nkdev.yakochat.util.UtilHandler.LogChat(UtilHandler.java:204) ~[?:?]
	at me.yakovliam.nkdev.yakochat.event.Chat.execute(Chat.java:20) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[kok.jar:?]
	... 17 more`

I seem to be having trouble getting the full error log, I'll keep working on that and post it here. Also, kok.jar is my nukkit java file. It doesn't have anything to do with that, does it? I don't have any nickname plugins enabled, nor do I have any other chat plugins. I do have LuckPerms installed, as well as PlaceholderAPI however and I will attempt this on a fresh server shortly.

**Comment by yakovliam** [comment]
The reason for this issue is that the plugin is made for a different version of Nukkit that you are running off of. Sadly the plugin will not work, and I do not intend to update as I am extremely busy with Spigot development.
